/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_vince_andwidget_jni_AndJNI */

#ifndef _Included_com_vince_andwidget_jni_AndJNI
#define _Included_com_vince_andwidget_jni_AndJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_vince_andwidget_jni_AndJNI
 * Method:    andloop
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_com_vince_andwidget_jni_AndJNI_andloop
  (JNIEnv *, jclass, jintArray);

#ifdef __cplusplus
}
#endif
#endif
